# Generated by Django 5.1.15 on 2026-05-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scholar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Female", "Female"),
                            ("Male", "Male"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("STEM", "STEM"), ("Non-STEM", "Non-STEM")],
                        max_length=30,
                    ),
                ),
                ("cohort", models.CharField(max_length=20)),
                (
                    "level_of_study",
                    models.CharField(
                        choices=[
                            ("Bachelor", "Bachelor"),
                            ("Masters", "Masters"),
                            ("PhD", "PhD"),
                            ("Diploma", "Diploma"),
                            ("Certificate", "Certificate"),
                        ],
                        max_length=40,
                    ),
                ),
                ("campus", models.CharField(max_length=120)),
                ("college", models.CharField(max_length=160)),
                ("nationality", models.CharField(max_length=100)),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("Undergraduate", "Undergraduate"),
                            ("Postgraduate", "Postgraduate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_alumni", models.BooleanField(default=False)),
                (
                    "expected_graduation_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("class_year", models.CharField(blank=True, max_length=20)),
                ("intake", models.CharField(blank=True, max_length=60)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["cohort", "category", "gender"],
                        name="scholars_sc_cohort_e4d65b_idx",
                    ),
                    models.Index(
                        fields=["campus", "college"],
                        name="scholars_sc_campus_4fdd85_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_alumni"],
                        name="scholars_sc_is_acti_3ff34f_idx",
                    ),
                ],
            },
        ),
    ]
