# Generated by Django 5.1.15 on 2026-05-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scholars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholar",
            name="accepted_offer_status",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="active_status_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="scholar",
            name="alumni_status",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="batch",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="scholar",
            name="by_enrollment",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="cell",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="consider_alumni_as_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scholar",
            name="date_of_leaving_program",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scholar",
            name="district",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scholar",
            name="dropout_active_status",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="family_parent_1",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="scholar",
            name="family_parent_2",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="scholar",
            name="family_parent_3",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="scholar",
            name="family_parent_phone_1",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="scholar",
            name="family_parent_phone_2",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="scholar",
            name="family_parent_phone_3",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="scholar",
            name="family_parent_relation_1",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="family_parent_relation_2",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="family_parent_relation_3",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="graduation_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scholar",
            name="home_country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="home_district",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="joining_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scholar",
            name="length_of_program",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="scholar",
            name="life_status",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="scholar",
            name="marital_status",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="scholar",
            name="nationality_country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="program",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="scholar",
            name="program_of_studies",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="scholar",
            name="promotion",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="province",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="region_category",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="replacement",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="sector",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="stem_category",
            field=models.CharField(
                blank=True,
                choices=[("STEM", "STEM"), ("Non-STEM", "Non-STEM")],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="scholar",
            name="student_no",
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="scholar",
            name="type_of_scholarship",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="village",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scholar",
            name="where_is_going",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="scholar",
            name="category",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="scholar",
            name="program_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Undergraduate", "Undergraduate"),
                    ("Postgraduate", "Postgraduate"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="scholar",
            index=models.Index(
                fields=["student_no"], name="scholars_sc_student_55ce89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scholar",
            index=models.Index(
                fields=["type_of_scholarship"], name="scholars_sc_type_of_7c8401_idx"
            ),
        ),
    ]
